### ISSUE TITLE
Regain compatibliity for iOS 7

### ISSUE THREAD

**Issue by mkempka** [eclipsesource/tabris#404]
When compiling for iOS 8.x, all goes well.

When I am trying to compile for iOS 7.0 or iOS 7.1 I get these errors

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in Tabris
  "_OBJC_CLASS_$_WKWebViewConfiguration", referenced from:
      objc-class-ref in Tabris
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jordiboehmelopez** [comment]
I'm not sure I understand what you are trying to do.
You always need to compile against the latest SDK (otherwise your app might get rejected by Apple and/or you loose 64bit/newer devices support).
This does not mean you'll loose compatibility to 7.x - Important is only to set the "Deployment Target" to 7.1. This will assure backwards compatibility.

Please close this issue if this answers your question / solves your problem.
