### ISSUE TITLE
This projects is ambiguous in regard to its licencing

### ISSUE THREAD

**Issue by pbeltranl** [eclipsesource/tabris#482]
Hi,

I've read on the EclipseSource web that using this project requires paying 9000 USD at least for non-open source products:

https://eclipsesource.com/products/tabris/pricing/

The commercial information is not connected to the project on Github in any way.

This is very unfair for developers that found Tabris for RAP on GitHub directly and they are not aware that this is really a commercial project. 

What if a developer spends months working on a commercial project using RAP and Tabris and after releasing it somebody asks him to pay a fee?

So, please, add some statement here on Github that this project requires payment for using it to avoid confusion and problems.

Thanks,
Pablo

**Comment by pbeltranl** [comment]
Another problem can happen if someone forks the project and releases the fork under the EPL license. That fork would also run under fees for others. 

I'm not sure if adding and statement to the README page on Github would resolve the problem.

IMHO (disclaimer: I'm no lawyer) you may want to use your own custom license instead of EPL to clarify this.

**Comment by ifurnadjiev** [comment]
We updated the README with additional information. Tabris for RAP is free. You can build your app by using the provided target platform (p2 repository) and use the pre-build launchers from Play Store or App Store to start it. We released these bundles under ELP, because Tabris for RAP is an extension to Eclipse RAP, which is licensed under EPL.
The commercial license is only needed if you want to create your own launcher and publish it to the stores.
